version: "3"
services:
  db:
    container_name: ${CONTAINER_PREFIX}_db
    image: postgres:${PGSQL_VERSION}
    ports:
      - ${PGSQL_PORT}:5432
    volumes:
      - ./sql/db-docker/backups:/var/backups
      - ./sql/db-docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    restart: always

  web:
    container_name: ${CONTAINER_PREFIX}_web
    image: 18110161/drupal-php8.1:latest #amd64 for common device.
    # image: thiennd0903/drupal-nginx-php:8.1.13 #arm64 for mac m1
    build: .
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./config/site-availables/drupal-recommend:/etc/nginx/sites-available/default
      - ./config/site-availables/drupal-https-recommend:/etc/nginx/sites-available/default-https
      - ./config/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./config/custom.conf:/etc/nginx/conf.d
      - ./config/drupal-php.ini:/usr/local/etc/php/conf.d/drupal-php.ini
      - ../.:/var/www/html
    depends_on:
      - db
    restart: always


volumes:
  db-data:
networks:
  default:
    external: true
    name: groceryShop
